### ISSUE TITLE
I followed commands but in If=5 Driver=(None)

### ISSUE THREAD

**Issue by fukaldev** [ngohaibac/Quectel_Modules_ADB_Issue#2]
I have EC25-E, and i'm trying connect to board via adb. First of all, i cannot see device. I followed your commands but in this time when i write 

`sudo cat /sys/kernel/debug/usb/devices`

I encountered with that

`I:* If#= 5 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=ff Prot=ff Driver=(none)`

**Comment by bacnh85** [comment]
@furkan-kalabalik sorry late reply as I don't look into my GitHub issue page.  For your module, can you show the full /sys/kernel/debug/usb/devices ? 

If you are using Standard EC25-E Module, then ADB interface is disabled, thus you can't access it.
