### ISSUE TITLE
Firmware EC25-A

### ISSUE THREAD

**Issue by daviidmart** [ngohaibac/Quectel_Modules_ADB_Issue#3]
Hi!

I am working with a development board that I create with the EC25-A module but I cannot get the device to appear in the adb. Do I need a special firmware?

Regards

![DEVBOARD](https://user-images.githubusercontent.com/10666050/110580373-2853ee80-812e-11eb-96b7-b139a41a9df9.jpg)

**Comment by bacnh85** [comment]
Yes. Pls contact your local FAE to get access to ADB if needed.
